/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevo;
import Conectar.Conectar;
import Sonidos.Sonidos;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Cambiar_usuario_contraseña extends javax.swing.JFrame {
 Conectar con=new Conectar();
 Sonidos s= new Sonidos();
 Connection cn;
 Statement st;
 ResultSet rs;
 String usuario;
 String contraseña;
    /**
     * Creates new form Cambiar
     */
    public Cambiar_usuario_contraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cambiarU = new javax.swing.JButton();
        cambiarC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mostrarUser = new javax.swing.JButton();
        mostrarContraseña = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambiar Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        cambiarU.setForeground(new java.awt.Color(255, 255, 255));
        cambiarU.setText("Cambiar Usuario");
        cambiarU.setContentAreaFilled(false);
        cambiarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarUActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        cambiarC.setForeground(new java.awt.Color(255, 255, 255));
        cambiarC.setText("Cambiar Contraseña");
        cambiarC.setContentAreaFilled(false);
        cambiarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarCActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cambiar Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, -1));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 160, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-go-back-24 (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        mostrarUser.setForeground(new java.awt.Color(255, 255, 255));
        mostrarUser.setText("Mostrar usuario actual");
        mostrarUser.setContentAreaFilled(false);
        mostrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarUserActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        mostrarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        mostrarContraseña.setText("Mostrar contraseña actual");
        mostrarContraseña.setContentAreaFilled(false);
        mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper_azul_oscuro_1920x1200_124.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cambiarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarUActionPerformed
   String usuario=user.getText();
  String sql="UPDATE login SET Usuario='"+usuario+ "' WHERE ID= "+1;
   try {
  cn=con.getConnection();
  st=cn.createStatement();
  st.executeUpdate(sql);
  s.Correcto();
  JOptionPane.showMessageDialog(null,"usuario modificado");
 user.setText("");
 }  
catch (Exception e){
s.Error();
 JOptionPane.showMessageDialog(null,"usuario no modificado"+ e);
      }
    }//GEN-LAST:event_cambiarUActionPerformed

    private void cambiarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarCActionPerformed
 String contraseña=pass.getText();
  String sql="UPDATE login SET Contraseña='"+contraseña+"' WHERE ID= '"+1+ " ' ";
  try {
 cn=con.getConnection();
 st=cn.createStatement();
st.executeUpdate(sql);
s.Correcto();
 JOptionPane.showMessageDialog(null,"contraseña modificada");       
 pass.setText("");
 }  
 catch (Exception e){
   s.Error();
   JOptionPane.showMessageDialog(null, "contraseña no modificada:"+e);
}
    }//GEN-LAST:event_cambiarCActionPerformed

    private void mostrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarUserActionPerformed
 String sql="SELECT Usuario FROM login WHERE ID= '"+1+ " ' ";
try {
 cn=con.getConnection();
 st=cn.createStatement();
 rs=st.executeQuery(sql);      
 while(rs.next()) {
 user.setText(rs.getString("Usuario"));
 }
}  
 catch (Exception e){
s.Error();
 }

    }//GEN-LAST:event_mostrarUserActionPerformed

    private void mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseñaActionPerformed
 String sql="SELECT Contraseña FROM login WHERE ID= '"+1+ " ' ";
 try {
 cn=con.getConnection();
 st=cn.createStatement();
 rs=st.executeQuery(sql);      
 while(rs.next()) {
 pass.setText(rs.getString("Contraseña"));
 }
}  
 catch (Exception e){
s.Error();
 }
    }//GEN-LAST:event_mostrarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiar_usuario_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiar_usuario_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiar_usuario_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambiar_usuario_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiar_usuario_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarC;
    private javax.swing.JButton cambiarU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mostrarContraseña;
    private javax.swing.JButton mostrarUser;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
