/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevo;
import javax.swing.table.DefaultTableModel;
import Sonidos.Sonidos;
import Conectar.Conectar;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Productos extends javax.swing.JFrame {
Conectar con=new Conectar();
Sonidos son=new Sonidos();
Connection cn;
Statement st;
ResultSet rs;
int id;
DefaultTableModel modelo;
Object [][]datos={};
Object[]columnas={"ID","PRODUCTOS","PRECIOXKILO","PRECIOXUNIDAD"};
public Productos() {
 initComponents();
 this.setLocationRelativeTo(null); //esto sirve para que la venta se muestre en el centro
 this.setResizable(false); //esto sirve para que no se pueda agrandar la ventana
 modelo=new DefaultTableModel(datos,columnas);
  tabla.setModel(modelo);
  Leer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        producto = new javax.swing.JTextField();
        mod = new javax.swing.JButton();
        precioxkilo = new javax.swing.JTextField();
        precioxunidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        borrar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-remove-24.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, 30));

        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 20));

        mod.setBackground(new java.awt.Color(0, 0, 0));
        mod.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        mod.setForeground(new java.awt.Color(255, 255, 255));
        mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registration-24.png"))); // NOI18N
        mod.setContentAreaFilled(false);
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modKeyPressed(evt);
            }
        });
        getContentPane().add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, 30));
        getContentPane().add(precioxkilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, -1));

        precioxunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioxunidadActionPerformed(evt);
            }
        });
        getContentPane().add(precioxunidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        pk.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        pk.setForeground(new java.awt.Color(255, 255, 255));
        pk.setText("PRECIO X KILO");
        getContentPane().add(pk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, -1));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRECIO X UNIDAD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, -1));

        borrar.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("Modificar");
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eliminar producto");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-plus-16.png"))); // NOI18N
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 50, 30));

        jLabel13.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 520, 80));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-go-back-24 (1).png"))); // NOI18N
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper_azul_oscuro_1920x1200_124.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addKeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  try {
   if(producto.equals("")||pk.equals("")){     
   JOptionPane.showMessageDialog(null,"campos vacios,complete las casillas para guardar");
   }
   else{
    Agregar();
    JOptionPane.showMessageDialog(null,"producto agregado");
 Actualizar();
   }
   }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_addActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Eliminar();
 Actualizar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void modKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modKeyPressed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
  Modificar();
   Actualizar();
    }//GEN-LAST:event_modActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoActionPerformed

    private void precioxunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioxunidadActionPerformed
        // TODO add your handling code here:
        precioxunidad.setText("0");
    }//GEN-LAST:event_precioxunidadActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int filas=tabla.getSelectedRow();
         id=Integer.parseInt((String)tabla.getValueAt(filas,0));
        String prod=(String)tabla.getValueAt(filas, 1);
        String pxk=(String)tabla.getValueAt(filas, 2);
        String pxc=(String)tabla.getValueAt(filas, 3);
        producto.setText(prod);
        precioxkilo.setText(pxk);
        precioxunidad.setText(pxc);
    }//GEN-LAST:event_tablaMouseClicked
public void Leer(){ // metodo para cargar los datos de la tabla productos de la bd y guardarla en un jtable
String sql="SELECT* FROM productos";
try{
cn=con.getConnection();
st=cn.createStatement();
rs=st.executeQuery(sql);
Object []datos = new Object[4]; //vector para guardar los datos de la bd
modelo=(DefaultTableModel)tabla.getModel();
while (rs.next()){
    datos[0]=rs.getString("id_prod");
    datos[1]=rs.getString("nombre_producto");
    datos[2]=rs.getString("precioxkilo");
    datos[3]=rs.getString("precioxunidad");
   modelo.addRow(datos); //vector para agregar los datos que pasamos de mysql a este para que se  agrege al modelo
}
tabla.setModel(modelo);//establece un modelo para agregar en las filas del jtable

}catch(Exception e){ 
    System.out.print(e);
}
}
    
 void Agregar(){ //metodo para agregar datos a la tabla producto desde java hacia la tabla de la bd 
String pro;
Float prexk,prexuni; //prexk=precio por kilo //prexuni=precio por unidad
int canti;
pro=producto.getText();
prexk=Float.parseFloat(precioxkilo.getText());
prexuni=Float.parseFloat(precioxunidad.getText());
String sql ="INSERT INTO productos (nombre_producto,precioxkilo,precioxunidad) VALUES ('"+pro+"', '"+prexk+"', '"+prexuni+"')";
 try{          
 cn=con.getConnection();
 st=cn.createStatement();
 st.executeUpdate(sql);        
 JOptionPane.showMessageDialog(null, "el producto se guardo correctamente");
 son.Correcto();
 }
 catch(Exception e){
 son.Error();
 JOptionPane.showMessageDialog(null, "el producto no Registrado:"+e);           
 }
 con.Cerrar();
}
 public void Eliminar(){ //metodo para eliminar un producto
  
 String sql="DELETE FROM productos WHERE id_prod= '"+id+"' ";
 try {
  cn=con.getConnection();
  st=cn.createStatement();
  st.execute(sql);
  JOptionPane.showMessageDialog(null,"producto eliminado");
  }catch(Exception e){
    JOptionPane.showMessageDialog(null,"erro al eliminar:"+e); 
 }
 con.Cerrar();
 }
 public void Modificar(){ //metodo modifica los datos del producto
     try {
 String pro=producto.getText();
 float prexk=Float.parseFloat(precioxkilo.getText());
 float  prexuni=Float.parseFloat(precioxunidad.getText());
String sql="UPDATE productos SET nombre_productos= '"+pro+"',precioxkilo='"+prexk+"',precioxunidad='"+prexuni+"' WHERE id_prod='"+id+"' ";
cn=con.getConnection();
st=cn.createStatement();
st.execute(sql);
JOptionPane.showMessageDialog(null,"producto modificado");
   }
  catch(Exception e){JOptionPane.showMessageDialog(null,"producto no modificado"+e);}
 
 
 }
 public void Actualizar(){ //metodo para actualizar el jtable cada vez que se modifica/elimina y guarda un dato
 modelo.setRowCount(0);
 Leer();
 };
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton atras;
    private javax.swing.JLabel borrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mod;
    private javax.swing.JLabel pk;
    private javax.swing.JTextField precioxkilo;
    private javax.swing.JTextField precioxunidad;
    private javax.swing.JTextField producto;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
