/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevo;
import Sonidos.Sonidos;
import Conectar.Conectar;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Registro_clientes extends javax.swing.JFrame {
 Sonidos s=new Sonidos();
 Conectar con=new Conectar();
 Connection cn;
 Statement st;
 ResultSet re;
 DefaultTableModel modelo;
 Object [][] datos={};
 Object[]columnas={"ID","NOMBRE","LOCALIDAD","DIRECCION"};
 public Registro_clientes() {
 initComponents();
 this.setLocationRelativeTo(null);
 this.setResizable(false);
 modelo=new DefaultTableModel(datos,columnas);
 tabla.setModel(modelo);
 leer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        mod = new javax.swing.JButton();
        localidad = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        borrar = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-remove-24.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 20));

        mod.setBackground(new java.awt.Color(0, 0, 0));
        mod.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        mod.setForeground(new java.awt.Color(255, 255, 255));
        mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registration-24.png"))); // NOI18N
        mod.setContentAreaFilled(false);
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modKeyPressed(evt);
            }
        });
        getContentPane().add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 50, 30));
        getContentPane().add(localidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, -1));
        getContentPane().add(calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOCALIDAD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, -1));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CALLE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 80, -1));

        borrar.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("Modificar");
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-go-back-24 (1).png"))); // NOI18N
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, -1, -1));

        jLabel8.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eliminar registro");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-plus-16.png"))); // NOI18N
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addKeyPressed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 30));

        jLabel13.setFont(new java.awt.Font("Frank Ruhl Hofshi", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Agregar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        tabla.setForeground(new java.awt.Color(0, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 680, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper_azul_oscuro_1920x1200_124.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void tablaMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        int filas=tabla.getSelectedRow();
         int id=Integer.parseInt((String)tabla.getValueAt(filas,0));
        String nom=(String)tabla.getValueAt(filas, 1);
        String local=(String)tabla.getValueAt(filas, 2);
        String calle=(String)tabla.getValueAt(filas, 3);
        nombre.setText(nom);
        localidad.setText(local);
        this.calle.setText(calle);
    }                                
    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        int filas=tabla.getSelectedRow();
 String sql="UPDATE clientes SET nombre=' "+nombre.getText()+"' ,localidad='"+localidad.getText()+"', direccion='"+calle.getText()+"' WHERE id_clientes='"+filas+"'  ";
  try {
 cn=con.getConnection();
 st=cn.createStatement();
 st.execute(sql);
 JOptionPane.showMessageDialog(null,"cliente  modificado ");
 s.Correcto();
 
 nombre.setText("");
 localidad.setText("");
 calle.setText("");       
 }catch (Exception e){
 s.Error();
 JOptionPane.showMessageDialog(null, "error al modificar:"+e);
 }
 con.Cerrar();
  
    }//GEN-LAST:event_modActionPerformed

    private void modKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modKeyPressed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed
 void Agregar(){
 String nom,apell,dni,local,cle, di,m,an;
 nom=nombre.getText();
 local=localidad.getText();
 cle=calle.getText();
String sql ="INSERT INTO clientes (nombre,localidad,direccion) VALUES ('"+nom+"', '"+local+"', '"+cle+"')";
 try{          
 cn=con.getConnection();
 st=cn.createStatement();
 st.executeUpdate(sql);        
 JOptionPane.showMessageDialog(null, "el cliente  se guardo correctamente");
 s.Correcto();
 }
 catch(Exception e){
 s.Error();
 JOptionPane.showMessageDialog(null, "el cliente  no Registrado:"+e);           
 }
 con.Cerrar();
}
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int filas=tabla.getSelectedRow();
 String sql="DELETE FROM clientes WHERE id_clientes='"+filas+"' ";
  try {
 cn=con.getConnection();
 st=cn.createStatement();
  st.execute(sql);
 JOptionPane.showMessageDialog(null, "cliente eliminado");
 s.Correcto();
 nombre.setText("");
 localidad.setText("");
 calle.setText("");
              
   }
 catch(Exception e){
   s.Error();
    JOptionPane.showMessageDialog(null, "Usuario no eliminado"+e);
       }
  con.Cerrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
  if(nombre.equals("")||localidad.equals("")||calle.equals("")){
   s.Error();
  JOptionPane.showMessageDialog(null, "El registro no se guardo!!");
  JOptionPane.showMessageDialog(null,"Por favor llene los datos para poder guardar");
} else{
 Agregar();
 s.Correcto();
  JOptionPane.showMessageDialog(null, "El registro se guardo correctamente en java");
   }
   }catch (Exception e){System.out.println(e);}
    }//GEN-LAST:event_addActionPerformed

    private void addKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addKeyPressed
public void leer(){
 String sql = "select * from clientes";
 try {
 cn = con.getConnection();
st = cn.createStatement();
 re= st.executeQuery(sql);
 Object[] persona = new Object[4]; 
  modelo = (DefaultTableModel) tabla.getModel();
 while (re.next()) {
 persona[0]=re.getString("id_clientes");
 persona[1] = re.getString("nombre");
 persona[2] = re.getString("localidad");
 persona[3] = re.getString("direccion");        
 modelo.addRow(persona);
 }
 tabla.setModel(modelo);
  }catch(Exception e){
  JOptionPane.showMessageDialog(null, e);
  }
 con.Cerrar();
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton atras;
    private javax.swing.JLabel borrar;
    private javax.swing.JTextField calle;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localidad;
    private javax.swing.JButton mod;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
